### ISSUE TITLE
Markus File Submission

### ISSUE THREAD

**Issue by zhtdavis** [alecjacobson/computer-graphics-bounding-volume-hierarchy#10]
It seems the required files on Markus is not consistent with the ones mentioned in readme.

AABBTree.cpp
box_box_intersect.cpp
find_all_intersecting_pairs_using_AABBTrees.cpp
insert_box_into_box.cpp
insert_triangle_into_box.cpp
nearest_neighbor_brute_force.cpp
point_AABBTree_squared_distance.cpp
point_box_squared_distance.cpp
**point_triangle_squared_distance.cpp (we are not asked to implement this one since it is already given in MeshTriangle.h)**
ray_intersect_box.cpp
ray_intersect_triangle.cpp
ray_intersect_triangle_mesh_brute_force.cpp
triangle_triangle_intersection.cpp

This is a list of files under current version of src dir.

**Comment by zhtdavis** [comment]
Oh,  It seems we also need to implement point_triangle_squared_distance.cpp but it is not mentioned in readme...

**Comment by velociraptor111** [comment]
![screen shot 2018-10-04 at 10 10 02 pm](https://user-images.githubusercontent.com/19272937/46512508-58428d80-c822-11e8-9647-65ff00caa57c.png)

???

**Comment by alecjacobson** [comment]
(I just added that; the readme was wrong. Thanks, @zhtdavis  for pointing it out).
