### ISSUE TITLE
data structure

### ISSUE THREAD

**Issue by shanchao95** [alecjacobson/computer-graphics-bounding-volume-hierarchy#16]
whats structure of V and F in "ray_intersect_triangle_mesh_brute_force.cpp", dont quite understand 
//   V  #V by 3 list of mesh vertex positions
//   F  #F by 3 list of triangle indices into rows of V

**Comment by RioAraki** [comment]
For anyone who also found this confusing, check: https://en.wikipedia.org/wiki/Wavefront_.obj_file
