### ISSUE TITLE
AABB left-right split

### ISSUE THREAD

**Issue by AbdallaGomaa** [alecjacobson/computer-graphics-bounding-volume-hierarchy#22]
For determining the left-right split, do we get the midpoint along the longest axis and then compare if the centres of the objects are less than the midpoint then they're on the left and if the centre is greater than the midpoint then they're on the right? If this is the case, what should we do if this split results in no objects on the left and all the objects on the right? (One of the objects is very wide while 2 others are completely on one side)

**Comment by RioAraki** [comment]
Prof said in today's class the easiest way is to assign one to the side with no object.
