### ISSUE TITLE
GLX: GLX version 1.3 is required ON CDF machines

### ISSUE THREAD

**Issue by Marina-t** [alecjacobson/computer-graphics-bounding-volume-hierarchy#25]
When I try to run './rays' on a CDF machine, I see the text output but then I get this message:
'GLX: GLX version 1.3 is required'
Has anyone encountered this issue before and is aware of a solution?

Thanks

**Comment by alecjacobson** [comment]
are you running over ssh or sitting at the computer? @johnkanji @cheshmi @psarahdactyl , could you check that the assignments run correctly on CDF asap.

**Comment by Marina-t** [comment]
Sorry, forgot to update the issue. It only happens when I ssh. 
It works fine when am at a workstation.

**Comment by alecjacobson** [comment]
Thanks. I think this makes sense. For SSH + OpenGL, you'll almost surely have to use X11 and this is more complicated to get working. I'm closing for now. If somebody figures out X11 on CDF, it'd be cool to see the answer.
