### ISSUE TITLE
Request for extention of assignment

### ISSUE THREAD

**Issue by cmrnihao** [alecjacobson/computer-graphics-bounding-volume-hierarchy#27]
Found that a lot of students got an unexpected amount of homework/exercise (411, 420 etc) this week so wonder if we can have an extension on this assignment for until weekend.

**Comment by ZhuaMei** [comment]
^

**Comment by MingrenChen** [comment]
^

**Comment by sandinbowl** [comment]
Agree. As well as 336.

**Comment by MingrenChen** [comment]
honestly as well as 469
