### ISSUE TITLE
"projection" in point_AABBTree_squared_distance

### ISSUE THREAD

**Issue by Marina-t** [alecjacobson/computer-graphics-bounding-volume-hierarchy#30]
This was asked before but the issue was closed without a response.
I am not sure what projection refers to in point_AABBTree_squared_distance?

thanks

**Comment by SmileWuji** [comment]
Short answer: you don't care. You just need to pass it to the object's point_squared_distance method (see MeshTriangle,h) and it will handle the value for you.

Long answer: 
For triangles, it is the point on a triangle being closest to the projection of your query point on the triangle's plane.
For point, it is the point itself.
