### ISSUE TITLE
Algorithm for triangle triangle intersection

### ISSUE THREAD

**Issue by RioAraki** [alecjacobson/computer-graphics-bounding-volume-hierarchy#33]
About triangle triangle intersection, I didnt see any algorithm on the book. After searching online I did find some paper talking about it like this one: http://fileadmin.cs.lth.se/cs/personal/tomas_akenine-moller/code/tritri_tam.pdf
, but it seems to be very time-consuming for me to implement it in C++.  I am wondering are we suppose to do research and implementation about triangle triangle intersection by ourselves? Or is there any easy reference somewhere that I missed?

**Comment by ghiacciozero** [comment]
You can see the lecture slide posted on the course website: https://github.com/alecjacobson/computer-graphics-csc418/blob/master/lectures/lecture4.pdf
It describes 2 algorithms about triangle and triangle intersection.

**Comment by zilixie** [comment]
make use of ray triangle intersect function maybe
