### ISSUE TITLE
Issues during CMAKE on WSL

### ISSUE THREAD

**Issue by s99090** [alecjacobson/computer-graphics-bounding-volume-hierarchy#37]
I am able to run CMAKE in release mode on WSL but I received the following msg:

`-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)`

Does it matter to not have the Vulkan library? or do I need to install Vulkan library for this assignment?

**Comment by abhimadan** [comment]
You don't need Vulkan for this assignment, but you do at least need OpenGL. If you're using WSL, the setup instructions are the same as Linux. See the footnote about Linux users at the bottom of  https://github.com/alecjacobson/computer-graphics-raster-images.

**Comment by s99090** [comment]
For my WSL, I also needed to install the following two libraries.
```
sudo apt-get install libxinerama1 libxinerama-dev
sudo apt-get install libxcursor-dev
```

**Comment by abhimadan** [comment]
Thank you for figuring this out! I'll add this to the readme for future reference.
