### ISSUE TITLE
Encountered CMake build error 

### ISSUE THREAD

**Issue by harrychenfeng** [alecjacobson/computer-graphics-bounding-volume-hierarchy#38]
Already pulled the latest assignment version from github. But still can not make a release/debug build. Getting the following message:
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LIBIGL: /home/fengchen/Desktop/CSC418_A4/libigl/include  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Creating target: igl::core (igl)
-- Creating target: igl::opengl (igl_opengl)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenGL.cmake:369 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  libigl/cmake/libigl.cmake:321 (find_package)
  cmake/FindLIBIGL.cmake:36 (include)
  CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/fengchen/Desktop/CSC418_A4/build/CMakeFiles/CMakeOutput.log".
See also "/home/fengchen/Desktop/CSC418_A4/build/CMakeFiles/CMakeError.log".

**Comment by abhimadan** [comment]
Which platform are you on? This typically means that you need to install OpenGL. If you're on Linux or WSL, you need to follow the steps outlined at the bottom of https://github.com/alecjacobson/computer-graphics-raster-images (see the footnote about Linux users).

**Comment by abhimadan** [comment]
This means that you don't have Xinerama installed. Try this (I'm not 100% sure this works as I'm not on Ubuntu):
`sudo apt-get install libxinerama1 libxinerama-dev`

**Comment by abhimadan** [comment]
In case you're still having issues, also try installing `libxcursor-dev` (from #37).

**Comment by harrychenfeng** [comment]
The issue is resolved. Thx!
