### ISSUE TITLE
Project Build Issue

### ISSUE THREAD

**Issue by zhtdavis** [alecjacobson/computer-graphics-bounding-volume-hierarchy#4]
Hi,

When I try to build the project in release mode, it reports the following error:
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.
Undefined symbols for architecture x86_64:
  "nearest_neighbor_brute_force(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, Eigen::Matrix<double, 1, 3, 1, 1, 3> const&, int&, double&)", referenced from:
      _main in distances.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [distances] Error 1
make[1]: *** [CMakeFiles/distances.dir/all] Error 2
make: *** [all] Error 2

It seems we are missing some header definition in distances.cpp. Thanks in advance!

**Comment by alecjacobson** [comment]
Thanks. Fixed in f9021d06bf1af7a5d097593fc2a38ea814b52153
