### ISSUE TITLE
Missing pthread.h and Vulcan when running cmake on Windows

### ISSUE THREAD

**Issue by Puneet119** [alecjacobson/computer-graphics-bounding-volume-hierarchy#47]
When I run cmake, the follow two error lines come up:

Looking for pthread.h - not found
Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)

Everything else seems to be fine.
Is there something I'm missing and should install?

Here is the full output when running cmake ..

-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.22.27905.0
-- The CXX compiler identification is MSVC 19.22.27905.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LIBIGL: D:/Solutions/MScAC Solutions/CSC2504 - Computer Graphics Solutions/computer-graphics-bounding-volume-hierarchy/libigl/include
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Creating target: igl::core (igl)
-- Creating target: igl::opengl (igl_opengl)
-- Found OpenGL: opengl32
-- Creating target: igl::opengl_glfw (igl_opengl_glfw)
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)
-- Using Win32 for window creation
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Solutions/MScAC Solutions/CSC2504 - Computer Graphics Solutions/computer-graphics-bounding-volume-hierarchy/build

**Comment by abhimadan** [comment]
It's not an issue. GLFW tries to use Vulkan if it can find it, but if not, it falls back on OpenGL.

**Comment by Puneet119** [comment]
Cool, thanks!

So the pthread.h missing is a non-issue as well?

**Comment by abhimadan** [comment]
Yes it's not an issue. You'll see that directly below that line that it found the Threads library instead, which fulfills the same purpose. In general, if cmake runs into an issue it can't recover from, it will tell you that it finished with errors. When it says stuff like "configuring done, generating done", it means that it finished successfully.

**Comment by Puneet119** [comment]
Thanks Abhi! Appreciate it :)
