### ISSUE TITLE
triangle_triangle_intersection algorithm question

### ISSUE THREAD

**Issue by AdaDong05** [alecjacobson/computer-graphics-bounding-volume-hierarchy#51]
Hi, so for the triangle_triangle_intersection algorithm, how to deal with coplanar triangles? Can I have my own strategy to decide intersect or not?

**Comment by abhimadan** [comment]
We talked about this during the tutorial, but for these sorts of special cases, you don't need to focus too much on them. The more important point is that your AABB intersection only impacts performance, not correctness, so as long as you don't see any output about mismatched results, you should be in good shape.
