### ISSUE TITLE
Unresolved external symbol with Eigen::Matrix3d::determinant() and Eigen::Vector3d::cross(v)

### ISSUE THREAD

**Issue by zhufyaxel** [alecjacobson/computer-graphics-bounding-volume-hierarchy#55]
Platform: Windows 10 with Visual Studio 2019
I have recursively clone all the components
----
For ray_intersection_triangle.cpp, I directly copy-paste the code I have during HW2(which works at that time), but can't go through the building session in current solutions. The Error Code is LNK 2019 which means the determinant() function is not supported there. 
A similar error happened with Vector3d.Cross() and Vector3D.Dot(), which is crucial but I have no idea why.
I've detailly checked the data and turned out to be that all the data are legal and being correctly instantiated before use. It is kinda weird for those things to happen.

Below are the error message prints
![InkedEigen_determinant_LI](https://user-images.githubusercontent.com/13378632/66452501-b9510280-ea2e-11e9-8d41-de813a080272.jpg)

![Eigen_cross](https://user-images.githubusercontent.com/13378632/66452428-6f681c80-ea2e-11e9-9154-869a0b4aa2bf.PNG)

**Comment by alecjacobson** [comment]
This has come up in other issues I think. If you use cross you need to
#include <Eigen/Geometry>

**Comment by zhufyaxel** [comment]
Hi Alec

Thanks for the reply, this solves the problem.
Shall I Close this issue or keep this open as a reference?
