### ISSUE TITLE
Can't use gdb

### ISSUE THREAD

**Issue by dakmcinnis** [alecjacobson/computer-graphics-bounding-volume-hierarchy#59]
**Environment:**
Device: MacBook Pro (Mid 2015)
OS: macOS Big Sur Version 11.5.2
Processor: 2.2 GHz Quad-Core Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Graphics: Intel Iris PRo 1536 MB

**Motivation:**
I got a segmentation fault when runnning `cd build-release && ./rays ../data/rubber-ducky.obj`. I want to use gdb to debug.

**Current Behaviour:**

Here are the attempts I made to debug, which all resulted in errors.

1. In release mode
<img width="600" alt="Screen Shot 2022-02-07 at 10 17 53 AM" src="https://user-images.githubusercontent.com/54950797/152817218-f2a512b3-f46d-4068-8659-cffffc69b442.png">

2. In debug mode
<img width="600" alt="Screen Shot 2022-02-07 at 10 18 17 AM" src="https://user-images.githubusercontent.com/54950797/152817280-e062b447-6f70-41e1-8b3d-783a8e6d429e.png">

3. In debug mode with sudo
<img width="600" alt="Screen Shot 2022-02-07 at 10 20 23 AM" src="https://user-images.githubusercontent.com/54950797/152817293-1d25a8ae-5ad2-48c6-b7e0-70b20db6e3c3.png">

**Questions:**

Am I doing something wrong in terms of setup? With no. 3 mentioning that "this version of macOS has System Integrity Protection", will I be able to run this?

**Comment by abhimadan** [comment]
If you're on a mac, use lldb instead. It has the same features as gdb but without these annoying code signing issues.
